SELECT * FROM TB_CLIENTES;
SELECT * FROM TB_PRODUTOS;

-- Select definindo a ordem das colunas apresentadas
SELECT PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA FROM TB_PRODUTOS;
SELECT PRODUTO, NOME FROM TB_PRODUTOS;

-- Select criando ALIAS, para mudar o nome de exibição das colunas
SELECT PRODUTO AS "CODIGO DO PRODUTO", NOME AS "NOME DO PRODUTO" FROM TB_PRODUTOS;