-- Select geral, com todos os dados da tabela
SELECT * FROM TB_CLIENTES;

-- Select filtrando dados da tabela como operadores lógicos
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = '25/03/92';
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE('25/03/1992', 'DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE('03/25/1992', 'MM/DD/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO > TO_DATE('03/25/1992', 'MM/DD/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO < TO_DATE('03/25/1992', 'MM/DD/YYYY');

-- Select filtrando dados usando a função TO_CHAR para considerar apenas o mês de nascimento
SELECT * FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') = 9;
SELECT DATA_NASCIMENTO FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') = 9;

-- Select definindo o campo de data e filtrando apenas o mês de nascimento
SELECT TO_CHAR(DATA_NASCIMENTO, 'DD/MM/YYYY') AS DATA_NASC FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') = 9;