-- Select básico
SELECT * FROM TABELA_DE_CLIENTES;
-- Select definindo colunas e ordenando
SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;
-- Select listando apenas registros distintos e ordenando
SELECT DISTINCT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;
-- Select definindo colunas, somando idades, agrupando cidades e ordenando
SELECT CIDADE, SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE;
-- Select definindo colunas, somando limite de crédito e agrupando cidades
SELECT CIDADE, SUM(LIMITE_DE_CREDITO), SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja' GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_PRODUTOS FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja' GROUP BY EMBALAGEM ORDER BY EMBALAGEM;